### ISSUE TITLE
memory leak in ngx_http_circle_gif_handler()?

### ISSUE THREAD

**Issue by krisk0** [evanmiller/nginx_circle_gif#2]
Will someone please tell me who and when frees memory taken at line 184

`image = ngx_palloc(r->pool, cglcf->circle_sizes[radius_index]);`

? IMHO this is as memory leak. I suggest adding `ngx_pfree(r->pool,image);` somewhere below.

**Comment by evanmiller** [comment]
I believe this will be freed when the request finishes.

**Comment by krisk0** [comment]
Indeed, experiment shows that memory usage does not increase even when `ngx_free()` is not called. 

So memory returned by `ngx_palloc()` is short-lived?

**Comment by evanmiller** [comment]
The memory is associated with the current HTTP request. When the request finishes, the memory is freed.
